### ISSUE TITLE
Push Notification for VoIP

### ISSUE THREAD

**Issue by karthikk2020** [edamov/pushok#108]
I am able to send push notification with this   but  I would like to define push type as VoIP .
 I have 2 questions .where can I define push type voip? which method it is ?. 

And I need to send specific payload .Like below 
"{\"aps\":{\"alert\":{\"loc-key\":\"" msg_id "\",\"loc-args\":[\"" arg "\"]},\"sound\":\"" soundfile "\""; "},\"call-id\":\"" 2223234424"\",\"pn_ttl\":" TITLE ",\"send-time\":\""date"\"}"

Can you please let me know how it can be done with this library

**Comment by edamov** [comment]
Hey @karthikk2020 
Here is short answers for your questions:
1) `$payload->setPushType('voip')`
2) `$payload->setCustomValue('key', 'value');`

**Comment by tjfayaz120** [comment]
Hi guys, I'm also trying to send a VoIP push, when I define the pushtype to voip using `$payload->setPushType('voip')` I get DeviceTokenNotForTopic error from the apn. If I remove this line then the push works as a normal message notification.

Any idea what I am doing wrong?
