### ISSUE TITLE
configurable curl options (avoid http_code 0)

### ISSUE THREAD

**Issue by tobiasbambullis** [edamov/pushok#109]
hey, 

great plugin! One small thing we had to change. In our productive system we got a http_code = 0 when calling $client->push(). 

So we changed Client.php to this: 

`private function prepareHandle(Notification $notification)
{
    $request = new Request($notification, $this->isProductionEnv);
    $ch = curl_init();

    $this->authProvider->authenticateClient($request);

    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); 
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
    curl_setopt_array($ch, $request->getOptions());
    curl_setopt($ch, CURLOPT_HTTPHEADER, $request->getDecoratedHeaders());

    // store device token to identify response
    curl_setopt($ch, CURLOPT_PRIVATE, $notification->getDeviceToken());

    return $ch;
}`

It would be a better solution if "Client" has a method like "setOptions" where you can set all curl options to do it!

**Comment by pnlarsson** [comment]
```
# curl https://api.push.apple.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
```

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962596

Debian removed GeoTrust cert that Apple CA was signed with (kind of).

This solved it for me:
```
wget --no-check-certificate -c https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem   \
    && mkdir /usr/local/share/ca-certificates/extra                                                                       \
    && mv GeoTrust_Global_CA.pem /usr/local/share/ca-certificates/extra/GeoTrust_Global_CA.crt                            \
    && update-ca-certificates
```
