### ISSUE TITLE
Class Pushok\AuthProvider\Token Not Found

### ISSUE THREAD

**Issue by grappetite-tahir** [edamov/pushok#113]
Before it was working and now I come back to this project and I can see its giving me this error.
I'm using PHP 7.2+
Laravel 5.8+

What I'm missing

All the traits are included 

use Pushok\AuthProvider;
use Pushok\Client;
use Pushok\Notification;
use Pushok\Payload;
use Pushok\Payload\Alert;

Still getting this issue.

This line
$authProvider = AuthProvider\Token::create($options);

I change this line to
$authProvider = Pushok\AuthProvider\Token::create($options);
or
$authProvider = \Pushok\AuthProvider\Token::create($options);

but no luck.

**Comment by oktaykalfa** [comment]
im having the same problem.

**Comment by stollr** [comment]
@grappetite-tahir can you have a look at https://github.com/edamov/pushok/issues/132#issuecomment-806875951

**Comment by bardia-far** [comment]
Hi
I still have this problem and comment number 132 does not solve the problem

**Comment by yasinahmed81** [comment]
I had this issue on my AWS instance, please install the extensions, `gmp` and `bcmath`, then restart your server.

**Comment by hkret4296** [comment]
add 
use Pushok\AuthProvider;

**Comment by Hardik4296** [comment]
use Pushok\AuthProvider;
$authProvider = AuthProvider\Token::create($options);

these 2 changes work for me.
