### ISSUE TITLE
development url

### ISSUE THREAD

**Issue by allphat** [edamov/pushok#117]
In Request class, url is set to
`const APNS_DEVELOPMENT_SERVER = 'https://api.development.push.apple.com';`

In Apple documentation, it is:
`Development server: api.sandbox.push.apple.com:443`

It seems to work but I wonder which one is correct

**Comment by edamov** [comment]
Seems it was `development` when I create this library a few years ago. And now they changed the URL for some reasons.
I found such [answer](https://stackoverflow.com/a/55871176/1806427)

**Comment by allphat** [comment]
Ok. So, it is not a big deal!
