### ISSUE TITLE
How to set certificate root authority?

### ISSUE THREAD

**Issue by upngo** [edamov/pushok#126]
I've set the .pem cert path, but there's no option to set the root certification authority - GeoTrust_Global_CA.pem
As described by https://developer.apple.com/library/archive/technotes/tn2265/_index.html#//apple_ref/doc/uid/DTS40010376-CH1-TNTAG31

As a result I get this error 
`SSL certificate problem: unable to get local issuer certificate`

If I add this to /etc/ssl/certs it doesn't help either

**Comment by baden32** [comment]
I think you're refering to an old reference about apns not related to the new apns/http2.
Useful info can be found here https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/

However, I also have y problem to understand how to setup the AAAA Certificate (I just opened a new issue about this).
Regards
Joel

**Comment by marcorocca** [comment]
I think you can use this method: https://github.com/edamov/pushok/issues/124#issuecomment-778685800

**Comment by upngo** [comment]
walkthrough of solution https://github.com/edamov/pushok/issues/128
