### ISSUE TITLE
requires lib-curl >=7.46.0

### ISSUE THREAD

**Issue by jacksonkr** [edamov/pushok#13]
Ubuntu 14.04 this works great. OSX 10.11.6 w/homebrew is another story:

```
$ composer require edamov/pushok:0.2.3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for edamov/pushok 0.2.3 -> satisfiable by edamov/pushok[0.2.3].
    - edamov/pushok 0.2.3 requires lib-curl >=7.46.0 -> the requested linked library curl has the wrong version installed or is missing from your system, make sure to have the extension providing it.


Installation failed, reverting ./composer.json to its original content.
```

Which I don't understand because I definitely have curl installed:
```
$ curl --version
curl 7.53.1 (x86_64-apple-darwin15.6.0) libcurl/7.53.1 OpenSSL/1.0.2k zlib/1.2.5 nghttp2/1.20.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy
```

And on top of that, it's picked up by php
```
$ php --ri curl

curl

cURL support => enabled
cURL Information => 7.43.0
Age => 3
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => No
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => No
HTTP2 => No
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-apple-darwin15.0
SSL Version => SecureTransport
ZLib Version => 1.2.5
```

Any ideas?

**Comment by mdio** [comment]
You PHP cURL says "cURL Information => 7.43.0" which is actually below the required >=7.46.0.
The php module for cURL and the curl binary are different things.
Try updating your php via homebrew since curl is bundled with php there.

**Comment by mludi** [comment]
So I had the same issue, I made it workign with

```
brew install php71 --with-homebrew-curl
brew install php71-gmp
brew install php71-intl                                                                                        ✘
```

I you haven't already install mcrypt too with
`brew install php71-mcrypt`

Finally I had to enable

`opcache.enable=1`

in

 `/usr/local/etc/php/7.1/php.ini`

 Now it's working fine :)

Ok, now I've the error message

```
FatalThrowableError in Integer.php line 95:
Call to undefined function FG\ASN1\Universal\gmp_init()
```

But _gmp_ is enabled. Damn.

**Comment by Albertscot** [comment]
I have the same issue like @jacksonkr 
When I tried to install the following command as per the solution by @mludi 

brew install php71 --with-homebrew-curl

It gives the following error.
Error: invalid option: --with-homebrew-curl

@mdio Can you please provide the steps to resolve this issue?

**Comment by mludi** [comment]
The issue was before 5 years. I don't use local php anymore.

**Comment by Albertscot** [comment]
Is there any solution for this?

**Comment by mdio** [comment]
Assuming that you're running macOS you should be getting a pretty recent PHP version compiled with a recent enough lib-curl if you're running `brew install php`.
That of course needs [Homebrew](https://brew.sh/).

If you ran that and it still didn't work, please post your output of:
```
php -v
php --ri curl
which php
```
