### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by yasinahmed81** [edamov/pushok#139]
Im getting this error when running `php composer require edamov/pushok`

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires edamov/pushok ^0.13.0 -> satisfiable by edamov/pushok[0.13.0].
    - edamov/pushok 0.13.0 requires ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.

Installation failed, deleting ./composer.json.

**Comment by edamov** [comment]
You should install and enable ext-intl extension on your system

**Comment by Dukeman330** [comment]
What parts of ext-intl does this package use? I'd prefer not to add this extension in production at this time if possible. I was running into the same error and was able to create a fork without the dependency and it seems to be running fine so far - at least for the cert-based notifications I'm sending.

**Comment by yasinahmed81** [comment]
My problem is solved.

Thank you for creating such a great framework, nice and easy to use.

⭐️ += 1

**Comment by yasinahmed81** [comment]
Problem solved.
