### ISSUE TITLE
How do you handle the response in Swift 3 it gives?

### ISSUE THREAD

**Issue by TheDagger** [edamov/pushok#14]
I have this code when I get the push notification, push notifications work by the way.

```
// Push notification received
    func application(_ application: UIApplication, didReceiveRemoteNotification data: [AnyHashable : Any]) {
        // Print notification payload data
        print("Push notification received: \(data)")
        
        let aps = data[AnyHashable("aps")]!
        
        print(aps)
    }

```
Here is the console output...

```
Push notification received: [AnyHashable("samplekey"): samplevalue, AnyHashable("aps"): {
    alert =     {
        body = hey;
        title = "Hello!";
    };
    sound = default;
}]
{
    alert =     {
        body = hey;
        title = "Hello!";
    };
    sound = default;
}

```
How do I get access to the variables in the alert object in Swift3?

**Comment by TheDagger** [comment]
Finally found answer, hope this is how you intended it

```
// Push notification received
    func application(_ application: UIApplication, didReceiveRemoteNotification data: [AnyHashable : Any]) {
        // Print notification payload data
        print("Push notification received: \(data)")
        
        let aps = data[AnyHashable("aps")]! as! NSDictionary
        
        let alert = aps["alert"]! as! NSDictionary
        
        let body = alert["body"] as! String
        let title = alert["title"] as! String
        
        print("body=\(body)")
        print("title=\(title)")
        
    }
```

**Comment by edwardmp** [comment]
This question is not really PushOK related, more Swift/iOS/APNS related. You should close this issue.

**Comment by AnkiReddyPolu** [comment]
// Push notification received
    func application(_ application: UIApplication, didReceiveRemoteNotification data: [AnyHashable : Any]) {
        // Print notification payload data
        print("Push notification received: \(data)")
        
        let aps = data[AnyHashable("aps")]! as! NSDictionary
        
        let alert = aps["alert"]! as AnyObject as! NSDictionary
        print("alert=\(alert)")
        
         let body = alert["body"] as AnyObject as! NSDictionary
        
        if let content_type = body["content_type"] as? String {
            print("content_type is : \(content_type)")
        }
        if let information = body["information"] as? String {
            print("information is : \(information)")
        }
  
        if let title = alert["title"] as? String {
            print("title is : \(title)")
        }
    }
