### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by neorbk** [edamov/pushok#144]
PHP Fatal Error: Uncaught Exception in `Client.php:161
Same issue thrown by another file (attached)
Stack trace:
# 0 /index.php(68): Pushok\Client->push()
# 1 {main}
      thrown in /pushok/src/Client.php on line 161

[Knuff.app.zip](https://github.com/edamov/pushok/files/7447875/Knuff.app.zip)

**Comment by neorbk** [comment]
This is from one of the server I am using -
Server - Nginx
`curl 7.79.1 (x86_64-pc-linux-gnu) libcurl/7.79.1 OpenSSL/1.0.2k-fips zlib/1.2.7
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
`


This is from another server I am using -
Server - Apache
`curl 7.79.1 (x86_64-redhat-linux-gnu) libcurl/7.79.1 NSS/3.67 zlib/1.2.7 libpsl/0.7.0 (+libicu/50.1.2) libssh2/1.10.0 nghttp2/1.33.0 OpenLDAP/2.4.44
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL UnixSockets`

Both server have PHP 7.3.32

**Comment by cloudex1** [comment]
May i know any update? I also facing this issue

**Comment by neorbk** [comment]
I had to compile curl with Openssl 1.1.1 and nghttp2. Which resolved the issue. However I performed this test on Ubuntu 20.10

I also noticed the issue remains when tried to compile curl on CentOS server.
