### ISSUE TITLE
Package spomky-labs/jose is abandoned, you should avoid using it. Use web-token/jwt-framework instead.

### ISSUE THREAD

**Issue by rickygm** [edamov/pushok#145]
Hi , when I run: composer require edamov/pushok:* 

I get this message and cannot continue: 

PHP Warning:  Module 'fileinfo' already loaded in Unknown on line 0
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
./composer.json has been updated
Running composer update edamov/pushok
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package spomky-labs/jose is abandoned, you should avoid using it. Use web-token/jwt-framework instead.
Generating autoload files
7 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

**Comment by edamov** [comment]
What version of the library do you use?
