### ISSUE TITLE
Package fgrosse/phpasn1 is abandoned

### ISSUE THREAD

**Issue by chbakouras** [edamov/pushok#157]
web-token/jwt-signature-algorithm-ecdsa ^2.0 requires web-token/jwt-signature ^2.0
web-token/jwt-signature ^2.0 requires web-token/jwt-core ^2.1 
web-token/jwt-core ^2.1 requires fgrosse/phpasn1 ^2.0

In web-token/jwt-core version ^3.0 they had removed fgrosse/phpasn1 require.

Is there any plan to upgrade web-token/jwt-signature-algorithm-ecdsa / web-token/jwt-key-mgmt to version 3?

**Comment by kohenkatz** [comment]
refs #158

**Comment by edamov** [comment]
@chbakouras @kohenkatz It is fixed in 0.14.4
