### ISSUE TITLE
Installation failed, reverting ./composer.json to its original content.

### ISSUE THREAD

**Issue by tamnv110** [edamov/pushok#16]
When i run code in terminal. It error 

> Installation failed, reverting ./composer.json to its original content.

`$ composer require edamov/pushok`

**Comment by edamov** [comment]
@tamnv110 
Try to run in verbose mode and tell me about output:
``` bash
$ composer require edamov/pushok -vvv
```

**Comment by chiluhimanshu2221** [comment]
All the minimum requirements has been set up. 
i.e. 
    PHP >= 7.0
    lib-curl >= 7.46.0 (with http/2 support enabled)
    lib-openssl >= 1.0.2e

Then I have tried with composer require edamov/pushok -vvv and its giving me the below error without specifying which thing is missing.

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package edamov/pushok No version set (parsed as 1.0.0) is satisfiable by edamov/pushok[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
`

**Comment by edamov** [comment]
Try to set specific version of library:
```bash
$ composer require edamov/pushok:0.2.5
```

**Comment by chiluhimanshu2221** [comment]
Thanks for the quick reply . But I am still getting the below error .

Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package edamov/pushok No version set (parsed as 1.0.0) is satisfiable by edamov/pushok[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.

**Comment by edamov** [comment]
Hm...
Try to add `"edamov/pushok":"0.2.*"` directly to `composer.json` and run `composer update`

**Comment by chiluhimanshu2221** [comment]
@edamov
Thanks for the immediate support and great library . Now the things have been successfully installed and I am able to send Push Notification to my devices `[statusCode:Pushok\Response:private] => 200 `.
Sorry to ask here but I have one more question about expire of token. Does your library  creates the token every time we run the code or it is using the previous token which was not expired yet within 1hr ?

**Comment by edamov** [comment]
Library creates the token every time when you run:
```php
$authProvider = AuthProvider\Token::create($options)
```
You can save this token, for example, in DB:
```php
$authProvider->get(); // return token
```
And later you can create `$authProvider` whith saved token:
```php
$authProvider = AuthProvider\Token::useExisting($token, $options);
```
So you should track token expiring time by your self. Maybe it is not very friendly for users of my library, but I don't know the better way to implement this feature and to save token between requests.

**Comment by chiluhimanshu2221** [comment]
Thanks for the details. useExisting is the functionality that I am looking
for. I think the database things can be easily implemented by the users and
based on that we can decide between create and useExisting.
