### ISSUE TITLE
0.15.x is no longer compatible with PHP 8.0

### ISSUE THREAD

**Issue by Dean151** [edamov/pushok#166]
Hi!

Turns out transient dependencies makes this library PHP 8.1+ only!

```
  Problem 1
    - web-token/jwt-core[v3.0.1, ..., 3.1.7] require php >=8.1 -> your php version (8.0.28) does not satisfy that requirement.
    - web-token/jwt-key-mgmt[v3.0.2, ..., 3.1.7] require php >=8.1 -> your php version (8.0.28) does not satisfy that requirement.
    - edamov/pushok[0.15.0, ..., 0.15.5] require web-token/jwt-key-mgmt ^3.0 -> satisfiable by web-token/jwt-key-mgmt[v3.0.1, ..., 3.1.7].
    - web-token/jwt-key-mgmt v3.0.1 requires web-token/jwt-core ^3.0 -> satisfiable by web-token/jwt-core[v3.0.1, ..., 3.1.7].
    - Root composer.json requires edamov/pushok ^0.15.0 -> satisfiable by edamov/pushok[0.15.0, ..., 0.15.5].
```

https://github.com/web-token/jwt-framework/blob/v3.0.1/composer.json#L55

Was it intended?
Because `jsonSerialize(): mixed` warning are still there on 0.14.0 and we would have definitely wanted to update this lib before to update our platforms to 8.1 :)

Maybe releasing a 0.14.3 with only the "ReturnWillChange" fix for PHP 8.0 ; and make 0.15.x PHP 8.1+ only would work?

**Comment by edamov** [comment]
Hi @Dean151 
It is a good idea to to add fix for support PHP 8.0 in 0.14.x, and use PHP 8.1+ starting from 0.15.x
It was not intended, but it should be fixed.
Unfortunately, I'm not available to add fix in coming days. But if you want, you can create pull request and I will merge it.

**Comment by Dean151** [comment]
Nice!
Could you just create and push an empty branch on `0.14.2` tag; so I can target it to create my PR that is PHP 8.0 compatible without the notices?
This branch could be named php-8.0 ; or 0.14.x? Your repo, your choice :)
Thanks!

**Comment by edamov** [comment]
Branch is created https://github.com/edamov/pushok/tree/php-8.0

**Comment by Dean151** [comment]
This issue is now resolved. I close it :)
