### ISSUE TITLE
Need to add custome key/value to aps

### ISSUE THREAD

**Issue by gsuzair** [edamov/pushok#174]
@edamov I need to add the 'attributes-type' and attributes' keys in aps, I added them using setCustomValue, but that doesnt work, I made changes in your Payload file, that worked but I cant push the changes made in vendor folder to my staging or live environment, is there any way I can add 'attributes-type' and attributes' keys to my aps payload for my liveactivity to start?

**Comment by edamov** [comment]
You can create Pull Request with your change, I will merge it and then it will be available in vendor folder.
Or you can fork this repository and create your own package with your fix.

**Comment by gsuzair** [comment]
Fixed the issue using fork. Thanks.
