### ISSUE TITLE
ErrorException in Client.php 99: Undefined offset: 1

### ISSUE THREAD

**Issue by mlusas** [edamov/pushok#19]
Hello, I've followed the Readme, and when triggering $client->push() via Laravel, I receive the follow error.  We've tried triggering a notification via [Node.js using this tutorial](https://eladnava.com/send-push-notifications-to-ios-devices-using-xcode-8-and-swift-3/) and we were able to successfully trigger a notification.

Any thoughts on how we may be able to fix or troubleshoot this?  Thank you,

```
ErrorException in Client.php line 99:
Undefined offset: 1
in Client.php line 99
at HandleExceptions->handleError(8, 'Undefined offset: 1', '/var/www/domain.com/qa/releases/20170424153008/vendor/edamov/pushok/src/Client.php', 99, array('mh' => resource, 'handles' => array(resource, resource), 'notification' => object(Notification), 'k' => 1, 'request' => object(Request), 'ch' => resource, 'active' => 0, 'mrc' => 0, 'responseCollection' => array(), 'handle' => resource, 'result' => null, 'headers' => '')) in Client.php line 99
at Client->push() in CharacterLikedJob.php line 75
at CharacterLikedJob->handle()
```

**Comment by isaiasmac** [comment]
Same problem here:

`PHP Notice:  Undefined offset: 1 in /vendor/edamov/pushok/src/Client.php on line 99`

**Comment by lucadegasperi** [comment]
Same problem here at the same line.

**Comment by edamov** [comment]
I think it is the same issue as here #7.
Please read my [answer(comment)](https://github.com/edamov/pushok/issues/7#issuecomment-276491673)

**Comment by lucadegasperi** [comment]
In my case this was indeed caused by curl not having http2 support on the Mac.

To solve I did the following things (assuming you are using homebrew):

First check if you actually have http2 support by trying to curl to an http2 url:

```
curl -I --http2 https://www.cloudflare.com/
```
this should result in an ```unsupported protocol``` error

Next install curl
```
brew install curl --with-nghttp2
brew link curl --force
```

Finally recompile php and tell it to use the curl library provided by homebrew

```
brew reinstall php71 --with-homebrew-curl
```

**Comment by antonioreyna** [comment]
Hello, I am getting the same error in:

vendor/edamov/pushok/src/Client.php:122

**Comment by edamov** [comment]
@antonioreyna Do you have `lib-curl` compiled with http/2 support on the server? What version of `pushok` library do you use?

**Comment by antonioreyna** [comment]
It was the http2 issue i just installed and now it works great. thank you!

> @antonioreyna Do you have `lib-curl` compiled with http/2 support on the server? What version of `pushok` library do you use?
