### ISSUE TITLE
lib-openssl 1.0.2j error

### ISSUE THREAD

**Issue by ing4prg** [edamov/pushok#3]
On CentOS 7 / PHP 7.0.14 with OpenSSL 1.0.2j installing with composer returns this error: "edamov/pushok 0.2.1 requires lib-openssl >=1.0.2.5 -> the requested linked library openssl has the wrong version installed or is missing from your system, make sure to have the extension providing it."

Can you fix it?

**Comment by edamov** [comment]
Hi @ing4prg,
I need to be sure that your PHP is compiled with the same `openssl` version which is installed on your system.
It can be the situation when the system has one version of `openssl` and php is compiled with another version of `openssl`. Are you sure that your PHP uses version `1.0.2j`? If you are sure I'll check it soon.

**Comment by ing4prg** [comment]
OpenSSL was upgraded to 1.0.2j. PHP not.
From phpinfo I get: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.0.14

**Comment by edamov** [comment]
So you need to recompile your PHP. For example, you can find some advices how to do it [here](http://stackoverflow.com/questions/41370391/how-to-compile-php-with-specific-versions-of-curl-and-openssl). Or you can use [docker image](https://hub.docker.com/r/edamov/pushok) I've created for this library but it uses PHP 7.0 not 7.1

**Comment by ing4prg** [comment]
Hi, using your docker image, I get this error message:
`# docker pull edamov/pushok`
Using default tag: latest
Pulling repository docker.io/edamov/pushok
Tag latest not found in repository docker.io/edamov/pushok

**Comment by edamov** [comment]
Try `docker pull edamov/pushok:7.0`

**Comment by edamov** [comment]
I close the issue, because the problem was not with library
