### ISSUE TITLE
How to send push with pem certificate file.

### ISSUE THREAD

**Issue by amitinfo86** [edamov/pushok#31]
Hello, 
You are using JWT for auth process, If we want to use pem certificate file for auth process how we can achieve this.

Thanks

**Comment by edamov** [comment]
Hi @amitinfo86 
The library doesn't supports Certificate-based authentication. This feature is the next on roadmap but I can't surely say when I will implement it

**Comment by jredoules** [comment]
Hello @edamov I opened a PR here : https://github.com/edamov/pushok/pull/63

**Comment by edamov** [comment]
Implemented in #63
