### ISSUE TITLE
Compatible with PHP7.2 ?

### ISSUE THREAD

**Issue by jpsarda** [edamov/pushok#34]
It seems that the library requires spomky-labs/jose 6.1.1 which is not compatible with PHP 7.2 because it uses a custom class Object which is not allowed since PHP 7.2

`Fatal error: Cannot use FG\ASN1\Object as Object because 'Object' is a special class name in ......../vendor/spomky-labs/jose/src/KeyConverter/ECKey.php on line 17`

spomky-labs/jose 7.0.0 has replaced Object by ASNObject which is compatible with PHP 7.2

EDIT actually I just saw you commited it 20 days ago, so I don't understand why I'm still getting the 6.1.1 dependancy when I use php composer.phar require edamov/pushok

Sorry for the useless post.

**Comment by edamov** [comment]
Hi @jpsarda 
I commited version 7.0.0 but I didn't create new tag of pushok library because build failed. So new changes are in the master branch.

**Comment by jpsarda** [comment]
Thx, I got it working with the following command :
`php composer.phar require --update-with-dependencies edamov/pushok:dev-master`

**Comment by edamov** [comment]
Fixed since version 0.4.1
