### ISSUE TITLE
Sometimes message not send to all the device tokens

### ISSUE THREAD

**Issue by lipflip** [edamov/pushok#35]
Sometimes (5 out of 10 times) not all messages were send to all the devicetokens.

We discovered that sometimes the connection breaks in the while loop in Client.php without any reason.
After investigation we discovered adding this line solves the problem:

...
while (($execrun = curl_multi_exec($mh, $running)) == CURLM_CALL_MULTI_PERFORM);
            
if ($execrun != CURLM_OK) {
  break;
}

//ADDED THIS AFTER CURLM_OK
if ($running && curl_multi_select($mh) === -1) {
  usleep(250);
}

while ($done = curl_multi_info_read($mh)) {
...

Don't know why. But after we had made this change, we hadn't had issues anymore.
Hope this helps someone.

Curl version: 7.52.1

**Comment by grizzly** [comment]
this also worked for me! thanks for that!

**Comment by eerison** [comment]
It's happen to me too :/

**Comment by eerison** [comment]
Sorry my problem is I was with my app open and when I send message don't show to me...
But when I outside app works normally :)
