### ISSUE TITLE
Composer conflict

### ISSUE THREAD

**Issue by oioio** [edamov/pushok#45]
Hello, I'm trying to use this library with [minishlink/web-push](https://packagist.org/packages/minishlink/web-push)
And there is a conflict in their dependencies 
web-token/jwt-core (minishlink/web-push -> web-token/jwt-signature) conflicts with spomky-labs/jose

I suppose that spomky-labs/jose should be replaced with [web-token/jwt-framework](https://packagist.org/packages/web-token/jwt-framework) 

[Migration guide](https://web-token.spomky-labs.com/migration/from-spomky-labs-jose)

**Comment by trevorgehman** [comment]
@edamov Would you like a PR for this?

**Comment by edamov** [comment]
@trevorgehman Sure :)

**Comment by koenhoeijmakers** [comment]
@trevorgehman how's the PR coming along?

`Spomky-Labs/jose` will lose active support at the end of 2018 (which is this month), so in case you haven't done any work on it yet i'd be happy to give it a shot :smile:

**Comment by trevorgehman** [comment]
> @trevorgehman how's the PR coming along?
> 
> `Spomky-Labs/jose` will lose active support at the end of 2018 (which is this month), so in case you haven't done any work on it yet i'd be happy to give it a shot 😄

Sure, I haven't started yet. Was waiting for the end of the semester. Go ahead!

**Comment by edamov** [comment]
It was solved in #52
