### ISSUE TITLE
composer require edamov/pushok ERROR

### ISSUE THREAD

**Issue by shnuzxw** [edamov/pushok#49]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/9431680/49512152-0c66a000-f8c8-11e8-993b-26221b5013b2.png">

**Comment by shnuzxw** [comment]
php7.1.19

**Comment by koenhoeijmakers** [comment]
You're missing the `gmp` extension, you can install it with `sudo apt install php7.1-gmp`
