### ISSUE TITLE
Problem with Title-loc-args

### ISSUE THREAD

**Issue by eiosca** [edamov/pushok#5]
Hi,
Thk's for your job.

I don't understand how to send title-loc-args.
I'use the method 
`$alert->setTitleLocArgs(`

but it dosen't works.

I'm trying manually with this

`$alert->setTitleLocArgs(["toto"])`

But in the json request i have

`string(221) "{"aps":{"alert":{"body":"Ggf","title-loc-key":"_NEW_MSG_FROM_","title-loc-args":{"0":"toto"}},"badge":1,"sound":"default"},"id":"4","prenom":"Iosca","nom":"Edouard","username":"eiosca","type":"message","notification":407}"`

I think the problem is because i have the index in the json request.
Maybe i not use this method correctly?

Thk's for your help.

**Comment by edamov** [comment]
Hi @eiosca.

Thanks for issue. I think it's the bug in the library, because the [official documentation](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH10-SW9) says the request should be like this:
``` json
{
    "aps" : {
        "alert" : {
            "loc-key" : "GAME_PLAY_REQUEST_FORMAT",
            "loc-args" : [ "Jenna", "Frank"]
        }
    }
}
```

**Comment by edwardmp** [comment]
@edamov 
Thanks for making this! This bug seems to be solvable by just changing the key constants for `loc-key` and `loc-args` in `Alert.php`, right? If so just respond and I'll file a pull request.

**Comment by edamov** [comment]
The first problem is about naming: `loc-key` should be instead of `title-loc-key`. The same with `loc-args`.
And the second problem is about value of `loc-args`: it should be `[ "Jenna", "Frank"]` instead of `{"0":"Jenna", "1":"Frank"}`

**Comment by edwardmp** [comment]
Thanks, that's what I meant. PR submitted for first problem.

Second problem, is this really still there as there are already tests in `AlertTest.php` that confirm the expected behavior is present?

**Comment by nickasd** [comment]
This issue has not been completely solved, I still get this problem mentioned by @edamov:

> And the second problem is about value of loc-args: it should be [ "Jenna", "Frank"] instead of {"0":"Jenna", "1":"Frank"}

I could solve it by removing `JSON_FORCE_OBJECT` from the argument list in Payload.php on line 278, but I'm not sure if this will break something else. Could you please have a look at this?
