### ISSUE TITLE
i need add custom key/value to aps

### ISSUE THREAD

**Issue by shnuzxw** [edamov/pushok#50]
![image](https://user-images.githubusercontent.com/9431680/49643255-2fbc5700-fa50-11e8-8c06-09794d48f33c.png)

**Comment by shnuzxw** [comment]
please add function to do this event

**Comment by koenhoeijmakers** [comment]
This is not possible ([apns does not allow this](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH10-SW1)).

You can use the following to add the custom data (but outside of the `aps` key).
```
$payload->setCustomValue('biz', [
    'amount' => 0.01,
    ... (other values)
]);
```

**Comment by shnuzxw** [comment]
![image](https://user-images.githubusercontent.com/9431680/49706607-d3c91c80-fc61-11e8-8c82-9bd5648d0a4c.png)

**Comment by shnuzxw** [comment]
The image is our biz online， five years。
I want to test apns，i will use pushok，but i can not put biz to aps。

**Comment by edamov** [comment]
You should use `setCustomValue` method as was mentioned above
