### ISSUE TITLE
Identifying responses to initially set messages

### ISSUE THREAD

**Issue by miraclebg** [edamov/pushok#55]
Hello,

I am trying to somehow find out which of the originally set messages for sending have failed (and identifying them correctly).

Is there a way to do this?

I've checked and i see that in the response only the failed ones are returned so there is no way to distinguish which message is this.

Say for example i am sending 3 messages and N2 fails - how can i identify it (may be with APNS_ID somehow?)

**Comment by edamov** [comment]
@miraclebg Did you try `getApnsId()` method on Response object?

**Comment by miraclebg** [comment]
And how do i relate ApnsId() to the originally set messages?

Example:

- I am sending 3 messages
- Second one fails
- Response contains just 1 item - the second failed one - but how do i find out that it was exactly that second original message?

**Comment by edamov** [comment]
@miraclebg You should add `apns-id` header for each request.
You can see more about it [here](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html) - Table 8-2APNs request headers

**Comment by miraclebg** [comment]
Awesome, thanks!
