### ISSUE TITLE
web-token 2?

### ISSUE THREAD

**Issue by CatoTH** [edamov/pushok#74]
Hi,

would you consider updating the dependency on `web-token` to version 2? It would mean having a min PHP version of 7.2, but according to #72 that seems to be on the agenda anyway...
I could give it a try and create a PR, if wanted.

**Comment by edamov** [comment]
Hi,

it will be good to update to a newer version of `web-token`. But do you know what improvements will we have if we move to web-token v2?
I think it is better to skip PHP 7.2 and move directly to PHP 7.3.
And I think it can be first major release of this library with such improvements.

**Comment by CatoTH** [comment]
Well, to be honest, my main motivation is that I want to use the recent version of web-token in my project for an API, while also using pushok, which doesn't work as it is because of version conflicts. I'm not sure if any of the new functionality of web-token 2 is of relevance for this project - except that the old branch will probably not receive updates forever...

**Comment by CatoTH** [comment]
Changes necessary seem to be be rather small: https://github.com/CatoTH/pushok/commit/bfeebac7f780ca8abd8fb005b76b499899341661
