### ISSUE TITLE
"minimum-stability" should be stable, not dev

### ISSUE THREAD

**Issue by peter279k** [edamov/pushok#75]
The `"minimum-stability"` block defined on `composer.json` means these all dependencies will install unstable versions.

IMHO, I suggest we can consider let `"minimum-stability"` be `stable` because it's proper for this package to install the stable versions of dependencies.

**Comment by edamov** [comment]
@peter279k Maybe this will help you - https://stackoverflow.com/a/23741001/1806427

**Comment by peter279k** [comment]
Hi @edamov, thanks for your reply.

This post you share looks great for us to accomplish issue.
