### ISSUE TITLE
ExpiredProviderToken : The provider token is stale and a new token should be generated

### ISSUE THREAD

**Issue by hnicolas-w** [edamov/pushok#92]
I get a lot of errors (in production) : ExpiredProviderToken : The provider token is stale and a new token should be generated.

I think this is due to the lib not refreshing the token as it should do according to Apple documentation.
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns

My workaround for now is to restart the worker but i think the lib should be proactive. I'm working on a PR. 

Anyone else experiencing this issue ?

**Comment by edamov** [comment]
The library can't persist token between requests so it doesn't provide refreshing token.
People who use the library should choose how to persist and how to update the token as they wish.
Do you have any ideas about how to persist token between requests?

**Comment by skoro** [comment]
I have also faced with this issue. After in a day my worker queue begins emit ExpiredProviderToken response status. As I can see on each push notifications a token is regenerated. Should I persist the token and on the next push use that token and refresh it after some time (the question - how to refresh ?) ?

**Comment by edamov** [comment]
@skoro 
From Apple [documentation](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns): 
> Refresh Your Token Regularly
For security, APNs requires you to refresh your token regularly. Refresh your token no more than once every 20 minutes and no less than once every 60 minutes. APNs rejects any request whose token contains a timestamp that is more than one hour old. Similarly, APNs reports an error if you recreate your tokens more than once every 20 minutes.
On your provider server, set up a recurring task to recreate your token with a current timestamp. Encrypt the token again and attach it to subsequent notification requests.

You can create new token (refresh) with `create()` method:
```
$authProvider = AuthProvider\Token::create($options);
```
After just call `$authProvider->get();` and you will get token which you can persist between requests.

If you need to use the same token in new requests you should use `useExisting()` method:
```
$authProvider = AuthProvider\Token::useExisting($tokenString, $options);
```
