### ISSUE TITLE
Not all notifications are sent

### ISSUE THREAD

**Issue by knyjoh** [edamov/pushok#99]
I have had repeated problems with not all notifications being sent.
The number of responses does not match with the number of notifications.

I have tried wrapping the call to `$client->push()` in a loop similiar to this:

```
do {
  $client->push();
} while (count($client->getNotifications()) > 0);
```

This helps. But there's still some notifications not being sent.
And preferably all this should be taken care of inside the push method.

My guess is that the problem has something to do with this line:

```
while ($running > 0 && $execrun === CURLM_OK) {
```

What if we get something else then CURLM_OK? Then we will not know what and the loop will just interrupt and the method return as if everything went well.

**Comment by knyjoh** [comment]
I think I've found where the problem lies.

```
// Continue to wait for more data if needed
do {
    $execrun = curl_multi_exec($mh, $running);
} while ($execrun === CURLM_CALL_MULTI_PERFORM);
```

If all handles finishes at about the same time, then `$running` here will be 0 because there are no more handle remaining.

Then the next loop runs which reads the responses and adds new handles (and removes them from the `$notifications` array). But `$running` is still 0, so the outer loop believe there's nothing more to do and stops.

The lower the number of `$nbConcurrentRequests`, the more frequently this happens. If set to 1, it happens every time, and is thus easily reproducible. But still, it does happen occasionally even with the default value of 20.

I believe this can be fixed by simply increasing `$running` every time a new handle is added.

**Comment by knyjoh** [comment]
Proposed fix: https://github.com/edamov/pushok/pull/102

**Comment by edamov** [comment]
@knyjoh Perfect! Thank you for this fix! It's merged now
